### ISSUE TITLE
django 3.1 + python3.7 无法正常使用 dj-db-conn-pool

### ISSUE THREAD

**Issue by HQ1363** [altairbow/django-db-connection-pool#14]
报错如下：
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/core/management/commands/makemigrations.py", line 101, in handle
    loader.check_consistent_history(connection)
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/db/migrations/loader.py", line 290, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/dj_db_conn_pool/core/mixins.py", line 65, in get_new_connection
    **pool_params
  File "/opt/workers/watt/.venv/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 97, in __init__
    Pool.__init__(self, creator, **kw)
TypeError: __init__() got an unexpected keyword argument 'key'

**Comment by HQ1363** [comment]
![image](https://user-images.githubusercontent.com/46860462/100694215-94091b80-33c9-11eb-9631-66dfdb588608.png)
找到bug了，作者这里应该是取key的变量，而不是纯key字符串，我提个pr

**Comment by altairbow** [comment]
fixed by @HQ1363

**Comment by HQ1363** [comment]
方便更新下pip包吗？

**Comment by altairbow** [comment]
> 方便更新下pip包吗？

节后吧……

**Comment by altairbow** [comment]
Done!
