### ISSUE TITLE
TypeError during attempted rollback

### ISSUE THREAD

**Issue by simernes** [altairbow/django-db-connection-pool#7]
During a loss of server connection due to timeout, the following error occurs. Not sure if this is actually a SQLAlchemy error or if it can be fixed in this library somehow.

    Traceback (most recent call last):
    File "/home/simernes/.local/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 2318, in do_rollback
        dbapi_connection.rollback()
    MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/home/simernes/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 693, in _finalize_fairy
        fairy._reset(pool)
    File "/home/simernes/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 880, in _reset
        pool._dialect.do_rollback(self)
    File "/home/simernes/.local/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 2320, in do_rollback
        if self.server_version_info < (12, 34, 56):
    TypeError: '<' not supported between instances of 'NoneType' and 'tuple'

**Comment by altairbow** [comment]
尝试使用这个版本，并将recycle设置为比MySQL wait_timeout小的值

[更新 MySQL Dialect：将server_version_info初始化值由None更改为(0,)](https://github.com/altairbow/django-db-connection-pool/commit/b956667f5001b346085fd53cdf6c804e96e54667)

**Comment by altairbow** [comment]
No feedback, Close.
